language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
services:
  - docker
before_install:
  # Repo for yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - sleep 3
  # Updating NPM to relevant version >= 3 on Node.JS LTS
  - npm i -g npm@^3
  - npm install -g webpack
  - npm install -g webpack-dev-server
  - npm install -g karma-cli
  - npm install -g protractor
  - npm install -g typescript
install:
  - yarn
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm start &
  - sleep 5
script:
  - npm run build:docker
cache:
  directories:
  - $HOME/.yarn-cache
sudo: required
